kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: workorder
  namespace: devops
spec:
  workspaces:
    - name: shared-data
    - name: github-ssh
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: source
          workspace: shared-data
        - name: ssh-directory
          workspace: github-ssh
      params:
        - name: url
          value: https://github.com/theautomation/workorder.git
        - name: revision
          value: main
        - name: deleteExisting
          value: "true"

    - name: build-push-image-api
      taskRef:
        name: buildah
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: container-image-registry.devops.svc:5000/tools/$(context.pipelineRun.name)-api:latest
        - name: DOCKERFILE
          value: ./deploy/container/Containerfile.api
        - name: PUSH_EXTRA_ARGS
          value: "--creds=${USERNAME}:${PASSWORD}"
        - name: TLSVERIFY
          value: "false"
        - name: FORMAT
          value: "docker"

    - name: build-push-image-worker
      taskRef:
        name: buildah
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: container-image-registry.devops.svc:5000/tools/$(context.pipelineRun.name)-worker:latest
        - name: DOCKERFILE
          value: ./deploy/container/Containerfile.worker
        - name: PUSH_EXTRA_ARGS
          value: "--creds=${USERNAME}:${PASSWORD}"
        - name: TLSVERIFY
          value: "false"
        - name: FORMAT
          value: "docker"

    # - name: replace-image-tag-api
    #   taskRef:
    #     name: replace-image-tag
    #   runAfter:
    #     - build-push-image-api
    #   workspaces:
    #     - name: source
    #       workspace: shared-data
    #   params:
    #     - name: IMAGE_REPO
    #       value: tools
    #     - name: IMAGE
    #       value: $(context.pipelineRun.name)
    #     - name: IMAGE_DIGEST
    #       value: $(tasks.build-push-image.results.IMAGE_DIGEST)

    # - name: replace-image-tag-worker
    #   taskRef:
    #     name: replace-image-tag
    #   runAfter:
    #     - build-push-image-worker
    #   workspaces:
    #     - name: source
    #       workspace: shared-data
    #   params:
    #     - name: IMAGE_REPO
    #       value: tools
    #     - name: IMAGE
    #       value: $(context.pipelineRun.name)
    #     - name: IMAGE_DIGEST
    #       value: $(tasks.build-push-image.results.IMAGE_DIGEST)

    # - name: git-push
    #   taskRef:
    #     name: git-cli
    #   runAfter:
    #     - replace-image-tag
    #   workspaces:
    #     - name: ssh-directory
    #       workspace: github-ssh
    #     - name: source
    #       workspace: shared-data
    #   params:
    #     - name: GIT_SCRIPT
    #       value: |
    #         git add ./deploy/k8s/manifest.yaml
    #         git commit -m "tekton set new image digest"
    #         git remote set-url origin git@github.com:theautomation/$(context.pipeline.name).git
    #         git push origin HEAD:main

    # - name: slack-message
    #   taskRef:
    #     name: send-to-channel-slack
    #   runAfter:
    #     - git-push
    #   params:
    #     - name: token-secret
    #       value: token-secret
    #     - name: message
    #       value: "Tekton had run $(context.pipelineRun.name) successfully"
