---
version: "3.8"
services:
  prd-workorder-app:
    image: docker-registry.theautomation.nl/coen/prd-workorder-app:latest
    container_name: prd-workorder-app
    restart: unless-stopped
    env_file: prd-workorder-app.env
    networks:
      - reverse-proxy
    ports:
      - 8050:8000
    volumes:
      - ./app:/code/app

networks:
  reverse-proxy:
    name: reverse-proxy
  vpn-server:
    driver: bridge
    name: vpn-server
    ipam:
      config:
        - subnet: 172.36.0.0/16
